### ISSUE TITLE
如何在当前页面展现

### ISSUE THREAD

**Issue by ShaochongDu** [tiantiankaixin/AppGuidDemo#1]
在当前页面使用时，直接闪退

AppGuidViewController *appGuid = [[AppGuidViewController alloc] initWithImageArray:@[@"guies01",@"guies02",@"guies03"] startBtnDistanceWithBottomArray:@[@50,@50,@50] needLoadVC:self];
        SharedApp.window.rootViewController = appGuid;

exceptionString:name:
NSInvalidArgumentException
reason:
Application tried to present modally an active controller <AppGuidViewController: 0x17ebfe40>.
callStackSymbols:

**Comment by tiantiankaixin** [comment]
应该是第二次展示时点击立即体验闪退的吧；第一次把引导页设置为rootvc时，会刷新整个视图层，当前视图会被从当前视图层级里移除，但是第二次再把引导页设置为rootvc时，因为引导页已经是root了所以不再刷新视图层，因为第一次点立即体验是从引导页present到当前页，所以这时候当前页已经在应用的视图层里了，然后你再moda就会出错。

**Comment by tiantiankaixin** [comment]
你的使用场景应该是，在当前页点击某个地方跳转到引导展示，展示完再回来；这样的话其实你自己写一个这种引导view（UIScrollview拖动展示），然后隐藏的时候做个缩放、渐隐动画就行了；如果需要有push或者present那种效果，比如push你可以把视图先放在keywindow的右侧，当需要出现时加个从右边移动过来的动画就ok了。

**Comment by ShaochongDu** [comment]
我自己写了一个，不过还是感谢你的回复

发自我的 iPhone
